---
- name: Update cache
  ansible.builtin.apt:
    update_cache: true
  run_once: true

- name: Install nginx and dynamic modules from repo
  ansible.builtin.apt:
    name:
    - nginx
    - libnginx-mod-http-cache-purge
    - libnginx-mod-http-headers-more-filter
    - libnginx-mod-http-brotli-filter
    - libnginx-mod-http-brotli-static
    state: present
  run_once: true

- name: Start Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
