php_version: "8.4"
php_packages:
  - "php{{ php_version }}"
  - "php{{ php_version }}-fpm"
  - "php{{ php_version }}-mysql"
  - "php{{ php_version }}-xml"
  - "php{{ php_version }}-zip"
  - "php{{ php_version }}-mbstring"
  - "php{{ php_version }}-gd"
  - "php{{ php_version }}-curl"
  - "php{{ php_version }}-intl"
  - "php{{ php_version }}-imagick"
  - "php{{ php_version }}-bcmath"
  - "php{{ php_version }}-soap"
  - "php{{ php_version }}-cli"
  - "php{{ php_version }}-common"
