# SSH
ansible_user: "{{ ANSIBLE_USER }}"
ansible_ssh_pass: "{{ ANSIBLE_SSH_PASS }}"

# Root password
ansible_become_pass: "{{ ANSIBLE_BECOME_PASS }}"

# MSMTP


# WordPress
project_directory: '/var/www/html/omega-cms/public_html'

# WordPress host configurations
zone: "Omega-Zone:10m"
rate: "60r/m"
gzip_comp_level: 3
gzip_types: "text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml"
error_log: "/var/log/nginx/error.log"
level: "error"
web_port: 80
domain_name: "omega-cms.omega.local"
index: index.php index.html index.htm
ssl_certificate: "/etc/nginx/ssl/omega-soc.run.place.cer"
ssl_certificate_key: "/etc/nginx/ssl/omega-soc.run.place.key"
