---
- name: Install MariaDB packages
  ansible.builtin.include_tasks: install.yml
  when: mariadb_install | default(true)

- name: Configure MariaDB
  ansible.builtin.include_tasks: configure.yml
  when: mariadb_configure | default(true)
