---
- name: Install prerequisites
  apt:
    name:
    - software-properties-common
    - gnupg
    - curl
    - ca-certificates
    - python3-pymysql
    state: present
    update_cache: yes
  run_once: true

- name: Add MariaDB GPG key
  ansible.builtin.get_url:
    url: https://mariadb.org/mariadb_release_signing_key.asc
    dest: /etc/apt/trusted.gpg.d/mariadb.gpg
    mode: '0644'
  run_once: true

- name: Add MariaDB repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64,arm64] https://mirror.creoline.net/mariadb/repo/{{ mariadb_version }}/ubuntu {{ ubuntu_codename }} main"
    state: present
    filename: mariadb
    update_cache: yes
  run_once: true

- name: Install MariaDB packages
  apt:
    name:
    - mariadb-server
    - mariadb-client
    state: present
    update_cache: yes

- name: Ensure MariaDB service is running
  service:
    name: mariadb
    state: started
    enabled: yes
  notify: Restart MariaDB

- name: Set MariaDB root password with mysqladmin
  ansible.builtin.shell: |
    mysqladmin -u root password "{{ mariadb_root_password }}"

- name: Remove anonymous users
  community.mysql.mysql_user:
    name: ''
    host_all: true
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Remove test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Disallow root login remotely
  community.mysql.mysql_user:
    name: root
    host: "{{ item }}"
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  with_items:
  - "%"
  - "{{ ansible_fqdn | default(ansible_host) }}"

- name: Create application database
  community.mysql.mysql_db:
    name: "{{ mariadb_database_name }}"
    state: present
    encoding: utf8mb4
    collation: utf8mb4_general_ci
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Create application user and grant privileges
  community.mysql.mysql_user:
    name: "{{ mariadb_user_name }}"
    password: "{{ mariadb_user_password }}"
    host: "{{ mariadb_user_host }}"
    priv: "{{ mariadb_database_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
