---
- name: Add PHP stable repository
  ansible.builtin.apt_repository:
    repo: 'ppa:ondrej/php'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Ubuntu"

- name: Check which PHP packages are available
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Ubuntu"

- name: Installing PHP and the required WordPress modules
  ansible.builtin.apt:
    name: "{{ php_packages }}"
    state: present
